import { PrTerminalGateAction, PrTerminalVerdict } from "./types.js";
import type { GuardrailState, HookInput, PrTerminalEvent, PrTerminalGateDecision } from "./types.js";
import {
  GH_PR_MERGED_LINE,
  GH_PR_CLOSED_LINE,
  GH_PR_REOPENED_LINE,
  PR_MONITOR_TERMINAL_LINE,
  MAX_PR_TERMINAL_BLOCKS,
  FORGE_TERMINAL_CMD,
} from "./constants.js";

// A forge success line is only evidence when *this call* is the one that
// produced it. Without that check any tool output merely containing the phrase
// arms the handoff — a grep of a test fixture did exactly that, twice, arming a
// post-merge handoff for a PR that does not exist and holding the turn open
// until the state was edited by hand.
//
// The monitor's own exit line is exempt: it is machine-generated by the watch
// loop and reaches the session through the monitor rather than a command the
// model chose to run.
function terminalProvenance(input: HookInput): { acceptsForgeLine: boolean } {
  const command = input.tool_input?.command;
  if (command === undefined) return { acceptsForgeLine: true };
  return { acceptsForgeLine: FORGE_TERMINAL_CMD.test(command) };
}

// gh writes its success line to stderr, the monitor exit line arrives on
// stdout/output, and a replayed Monitor notification may carry it in content —
// scan all four.
export function detectPrTerminal(input: HookInput): PrTerminalEvent | null {
  if (input.tool_name !== "Bash" && input.tool_name !== "Monitor") return null;
  const response = input.tool_response;
  const provenance = terminalProvenance(input);
  const haystack = [response?.stdout, response?.stderr, response?.output, response?.content]
    .filter((part): part is string => typeof part === "string")
    .join("\n");
  const mergedMatch = provenance.acceptsForgeLine ? haystack.match(GH_PR_MERGED_LINE) : null;
  if (mergedMatch) {
    return { prNumber: Number(mergedMatch[1]), verdict: PrTerminalVerdict.Merged };
  }
  const closedMatch = provenance.acceptsForgeLine ? haystack.match(GH_PR_CLOSED_LINE) : null;
  if (closedMatch) {
    return { prNumber: Number(closedMatch[1]), verdict: PrTerminalVerdict.Closed };
  }
  const monitorMatch = haystack.match(PR_MONITOR_TERMINAL_LINE);
  if (monitorMatch) {
    return {
      prNumber: Number(monitorMatch[1]),
      verdict: monitorMatch[2] === "MERGED" ? PrTerminalVerdict.Merged : PrTerminalVerdict.Closed,
    };
  }
  return null;
}

/** The pull-request number a `gh pr reopen` success line names, or null when the tool output carries no reopen. */
export function detectPrReopened(input: HookInput): number | null {
  if (input.tool_name !== "Bash") return null;
  if (!terminalProvenance(input).acceptsForgeLine) return null;
  const response = input.tool_response;
  const haystack = [response?.stdout, response?.stderr, response?.output, response?.content]
    .filter((part): part is string => typeof part === "string")
    .join("\n");
  const reopenedMatch = haystack.match(GH_PR_REOPENED_LINE);
  return reopenedMatch ? Number(reopenedMatch[1]) : null;
}

// Retract a terminal verdict the reopen un-did. Drops the number from BOTH sets:
// out of `terminalPending` because no post-merge handoff is owed on a change
// that is open again, and out of `terminalHandled` so a later, genuine close
// re-arms the gate instead of being swallowed as already-handled.
//
// This deliberately does NOT rewind `terminalBlockCount` — only the offer does
// (applyNextOptionsOffered). Clearing the pending set can only ever reduce
// nagging, but rewinding the counter here would let a close/reopen cycle hand
// the gate a fresh budget each time and turn the cap into an unbounded loop.
export function applyPrReopened(state: GuardrailState, prNumber: number): GuardrailState {
  const pending = state.terminalPending ?? [];
  const handled = state.terminalHandled ?? [];
  if (!pending.includes(prNumber) && !handled.includes(prNumber)) return state;
  return {
    ...state,
    terminalPending: pending.filter((number) => number !== prNumber),
    terminalHandled: handled.filter((number) => number !== prNumber),
  };
}

// Arm the handoff for a newly terminal PR. Returns the same reference when the
// PR is already pending or already handled so the caller can skip the write and
// the repeat nudge — the same terminal line can resurface later in the session
// (a log tail, a replayed monitor notification) and must not re-arm a gate the
// offer already cleared.
export function applyPrTerminalDetected(state: GuardrailState, prNumber: number): GuardrailState {
  const pending = state.terminalPending ?? [];
  const handled = state.terminalHandled ?? [];
  if (pending.includes(prNumber) || handled.includes(prNumber)) return state;
  return { ...state, terminalPending: [...pending, prNumber] };
}

// The ONLY exit: an AskUserQuestion call while a terminal PR is pending. Moves
// the pending PRs to handled and resets the block counter. Nothing else —
// not a passing unit test, not a tick, not another Bash call — may clear the
// pending set or rewind the counter: any other reset path lets routine
// activity turn the 3-block cap into an unbounded nag loop.
export function applyNextOptionsOffered(state: GuardrailState): GuardrailState {
  const pending = state.terminalPending ?? [];
  if (pending.length === 0) return state;
  return {
    ...state,
    terminalPending: [],
    terminalHandled: [...(state.terminalHandled ?? []), ...pending],
    terminalBlockCount: 0,
  };
}

// Decide what the Stop hook does when a terminal PR's handoff is still owed.
//
// - `None`    — nothing pending (no terminal PR, or the offer already ran).
// - `Block`   — refuse the turn end so the handoff runs; increments blockCount.
// - `Release` — blocked MAX_PR_TERMINAL_BLOCKS times already; allow the turn to
//               end so an un-offerable situation can't trap the session. The
//               release is unconditional and the counter only ever moves up
//               (here) or back to zero (applyNextOptionsOffered).
export function prTerminalGateDecision(
  state: GuardrailState,
  maxBlocks: number = MAX_PR_TERMINAL_BLOCKS,
): PrTerminalGateDecision {
  const blockCount = state.terminalBlockCount ?? 0;
  if ((state.terminalPending ?? []).length === 0) {
    return { action: PrTerminalGateAction.None, blockCount: blockCount };
  }
  if (blockCount >= maxBlocks) {
    return { action: PrTerminalGateAction.Release, blockCount: blockCount };
  }
  return { action: PrTerminalGateAction.Block, blockCount: blockCount + 1 };
}
